# base image
FROM centos

# MAINTAINER
MAINTAINER loveward94@gmail.com
EXPOSE 8080
EXPOSE 5000

# running required command
RUN yum update -y
RUN yum install java wget -y
RUN wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
RUN rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
RUN yum install -y jenkins 

# copy file
ADD apache-tomcat-9.0.19.tar.gz /tomcat
RUN rm -rf /tomcat/apache-tomcat-9.0.19/webapps/*
RUN cp /usr/lib/jenkins/jenkins.war /tomcat/apache-tomcat-9.0.19/webapps/ROOT.war

# install git
RUN yum install -y git 

# install nodejs
RUN curl -sL https://rpm.nodesource.com/setup_11.x | bash -
RUN yum install nodejs -y

# install yarn
RUN curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
RUN yum install -y yarn

# download & decompress wine
ADD wine-4.0.tar.xz /usr/src
RUN yum groupinstall 'Development Tools' -y
RUN yum install libX11-devel freetype-devel zlib-devel libxcb-devel -y

# build wine
WORKDIR /usr/src/wine-4.0
RUN ./configure --enable-win64 --without-x
RUN make -j8
RUN make install

# install mono
RUN rpm --import "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
RUN curl https://download.mono-project.com/repo/centos7-stable.repo | tee /etc/yum.repos.d/mono-centos7-stable.repo
RUN yum install mono-devel -y

# install python
RUN yum install epel-release -y
RUN yum install python36 -y

# define ENTRYPOINT
#ENTRYPOINT ["/tomcat/apache-tomcat-9.0.19/bin/catalina.sh","run"]
ADD run.sh /root
RUN chmod 755 /root/run.sh
CMD ["/bin/bash","/root/run.sh"]

